version: '2'
services:
  redis:
    image: "redis:alpine"
  postgres:
    image: "postgres:9.4"
    environment:
     POSTGRES_PASSWORD: postgres
     POSTGRES_USER: postgres
  web:
    build: .
    ports:
     - "8080:8080"
    volumes:
     - .:/usr/src/app
    depends_on:
      - postgres
      - redis
    command: ["./wait_for_it.sh", "postgres:5432", "--", "node", "server.js" ]
